### ISSUE TITLE
OSX ARM migrator doesn't "see" this feedstock

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/faiss-split-feedstock#38]
Hey @conda-forge/help-osx-arm64, there was a question on the upstream issue tracker to build for osx-arm, and I was wondering why the migrator hasn't come past this feedstock.

I cannot find it listed under https://conda-forge.org/status/#long_migrations, so for some reason, the migrator doesn't "know" about this feedstock.

How can I (re-)trigger the migrator?

**Comment by isuruf** [comment]
See docs on https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

**Comment by h-vetinari** [comment]
Thanks, will do!
