### ISSUE TITLE
Support ppc64le cuda

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/faiss-split-feedstock#6]
Some preparatory work done in https://github.com/conda-forge/docker-images/pull/113, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/104. Still blocked at least on https://github.com/AnacondaRecipes/cudatoolkit-feedstock/pull/6

**Comment by h-vetinari** [comment]
I'm guessing an even earlier step is building for ppc64le at all. I'm not sure why this feedstock isn't being picked up for the ppc/aarch migration. @conda-forge/help-ppc64le

**Comment by jakirkham** [comment]
Think this was done in PR ( https://github.com/conda-forge/faiss-split-feedstock/pull/58 )

Should we close?
